In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt

In [35]:
in_data=np.around((np.random.rand(3,4)),decimals=2)

In [36]:
print (in_data)
print("shape input=", in_data.shape)

[[0.77 0.36 0.32 0.96]
 [0.24 0.58 0.69 0.97]
 [0.36 0.48 0.85 0.76]]
shape input= (3, 4)


In [37]:
filter2d=np.around((np.random.rand(2,2)),decimals=2)
print(filter2d)

[[0.8  0.17]
 [0.94 0.58]]


In [38]:
print (in_data[2,1])

0.48


In [39]:
#convlution process for 2D data
# func return size of outro data
def outro_size(in_data,filter2d,stride,pad):
    n,m=in_data.shape
    v,f=filter2d.shape #k=v,f respectively 
#     pad=0
#     stride=1
    outro_l=int(((n-v+2*pad)/(stride))+1)
    outro_k=int(((m-f+2*pad)/(stride))+1)
    return (outro_l,outro_k)


In [58]:
print(outro_size(inp,filter2d,1,0))
outro_dim=outro_size(inp,filter2d,1,0)
out=np.zeros(outro_dim)
out

(2, 3)


array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
#convolution function
def conv2d(in_data,filter2d,out):
    n,m=in_data.shape
    v,f=filter2d.shape
    l,k=out.shape
    print("here we go",out)
#     outro_dim=outro_size(in_data,filter2d,stride,pad)
#     out=np.zeros(outro_dim) # deleted in case of memory leak
    for i in range(l):
        for j in range(k):
            for x in range(v):
                for y in range(f):
#                     print("before multiplication",out[i,j])
                    out[i,j]+=filter2d[x,y]*in_data[i+x][j+y]
#                     print("after multiplication",out[i,j])

In [60]:
conv2d(in_data,filter2d,out)
out

here we go [[0. 0. 0.]
 [0. 0. 0.]]


array([[1.2392, 1.2878, 1.6304],
       [0.9074, 1.5255, 1.9567]])

In [77]:
def matrix_flatten_size(matrix):
    d,n=matrix.shape
    return (1,n*d)

In [78]:
out_flattened=np.zeros(matrix_flatten_size(out))

In [82]:
def matrix_flatten(matrix_in, matrix_out):
    d,n=matrix_in.shape
    for i in range(d):
        for j in range(n):
            matrix_out[0,i*n+j]=matrix_in[i,j]
    

In [83]:
in_data=np.zeros(matrix_flatten_size(out))
matrix_flatten(out,in_data)

In [81]:
print(in_data.shape)
print(out.shape)

(1, 6)
(2, 3)


In [84]:
out

array([[1.2392, 1.2878, 1.6304],
       [0.9074, 1.5255, 1.9567]])

In [85]:
in_data

array([[1.2392, 1.2878, 1.6304, 0.9074, 1.5255, 1.9567]])

In [86]:
def activation (in_data):
    d,n=in_data.shape
    for i in range (d):
        for j in range (n):
            in_data[i,j]=((1)/(1+2.71828**(-1*in_data[i,j])))

In [87]:
activation(in_data)

In [114]:
print(in_data)
in_data.shape

[[0.77542459 0.78377444 0.83622428 0.7124677  0.82134681 0.87617523]]


(1, 6)

In [127]:
d_previous,neurons_previous=in_data.shape
neurons_current=1
d_current=1
Weight_matrix=np.random.rand(neurons_previous,neurons_current)
# Weight_matrix=np.zeros((neurons_current,neurons_previous))

print(Weight_matrix)

[[0.97362752]
 [0.86341054]
 [0.2059069 ]
 [0.51877051]
 [0.90128793]
 [0.88760212]]


In [128]:
def fully_connected_layer(in_data, weights):
    return (np.matmul(in_data,weights))

    

In [132]:
out= fully_connected_layer(in_data, Weight_matrix)

In [133]:
print(out)

[[3.49145036]]


In [138]:
def cost_function_se(label, out): #only for 1x1 D out! (output is a 1x1 tensor\matrix)
    return(0.5*(out.item()-label)**2)
    
    

In [144]:
label=1 # just for instance
print(cost_function_se(label,out))

3.1036624515162092
